(function(){
  'use strict';
  var VERSION='OS v6.4';
  var KEY='cybershield_os_v6_4_state';
  var state={step:0,data:null,activeReport:'Executive Risk Summary'};
  var $=function(s,r){return (r||document).querySelector(s)};
  var $$=function(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))};
  function pct(n){return Math.max(0,Math.min(100,Math.round(n)))}
  function money(n){return '$'+Math.round(n).toLocaleString()}
  function band(n){return n>=82?'Resilient':n>=64?'Developing':'Elevated'}
  function cls(n){return n>=82?'green':n>=64?'yellow':'red'}
  function cap(s){return String(s||'').charAt(0).toUpperCase()+String(s||'').slice(1)}
  function save(){localStorage.setItem(KEY,JSON.stringify({data:state.data,activeReport:state.activeReport}))}
  function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||'{}');state.data=x.data||null;state.activeReport=x.activeReport||'Executive Risk Summary'}catch(e){}}
  function route(name){
    if(!state.data && ['briefing','actions','scenario','trust','memory','reports'].indexOf(name)>-1){name='assessment'}
    $$('.view').forEach(function(v){v.classList.toggle('active',v.id===name)});
    $$('.nav a').forEach(function(a){a.classList.toggle('active',a.dataset.route===name)});
    location.hash=name;
    $('#app').focus({preventScroll:true}); window.scrollTo({top:0,behavior:'smooth'});
    if($('#primaryNav')) $('#primaryNav').classList.remove('open');
  }
  function wireRoutes(){
    document.addEventListener('click',function(e){
      var b=e.target.closest('[data-route]'); if(!b)return; e.preventDefault(); route(b.dataset.route);
    });
    $('#menuBtn').addEventListener('click',function(){var n=$('#primaryNav'); n.classList.toggle('open'); this.setAttribute('aria-expanded',n.classList.contains('open'))});
    $('#resetBtn').addEventListener('click',function(){ if(confirm('Reset the CyberShield assessment and generated briefing?')){localStorage.removeItem(KEY);state.data=null;state.step=0;updateGate();showStep(0);route('assessment')}});
    window.addEventListener('hashchange',function(){route((location.hash||'#overview').replace('#',''))});
  }
  function updateGate(){
    $$('.requires-data').forEach(function(x){x.style.opacity=state.data?'1':'.45';x.setAttribute('aria-disabled',state.data?'false':'true')});
    $('#assessmentNav').style.display=state.data?'none':'';
  }
  function showStep(n){
    state.step=Math.max(0,Math.min(5,n));
    $$('.step').forEach(function(s,i){s.classList.toggle('active',i===state.step)});
    $('#progressBar').style.width=((state.step+1)/6*100)+'%';
    $('#stepLabel').textContent='Step '+(state.step+1)+' of 6';
    $('#prevBtn').disabled=state.step===0;
    $('#nextBtn').classList.toggle('hidden',state.step===5);
    $('#submitBtn').classList.toggle('hidden',state.step!==5);
  }
  function wireForm(){
    $('#prevBtn').addEventListener('click',function(){showStep(state.step-1)});
    $('#nextBtn').addEventListener('click',function(){showStep(state.step+1)});
    $('#assessmentForm').addEventListener('submit',function(e){e.preventDefault();state.data=generate(readInputs());save();updateGate();renderAll();route('briefing')});
  }
  function readInputs(){
    var val=function(id){return $('#'+id).value};
    var goalLabels={executive:'Executive CyberShield Review',trust:'Operational Trust Assessment',ai:'AI Governance Boundary Review',resilience:'Operational Resilience Briefing',vendor:'Vendor Governance Review'};
    var i={personName:val('personName').trim()||'Executive',orgName:val('orgName').trim()||'Your Organization',industry:val('industry'),valueRange:val('valueRange'),reviewGoal:val('reviewGoal'),primaryConcern:val('primaryConcern'),controls:val('controls'),evidence:val('evidence'),aiUse:val('aiUse'),dataSensitivity:val('dataSensitivity'),incident:val('incident'),cadence:val('cadence'),owner:val('owner'),audience:val('audience'),date:new Date().toLocaleDateString()};
    i.reviewGoalLabel=goalLabels[i.reviewGoal]; i.recommendedOwner=i.owner||recommendOwner(i); return i;
  }
  function recommendOwner(i){if(i.primaryConcern==='ai')return 'CIO / CTO'; if(i.primaryConcern==='vendor')return 'COO'; if(i.primaryConcern==='audit')return 'CISO / Security Lead'; if(i.primaryConcern==='ownership')return 'CEO / President'; if(i.primaryConcern==='incident')return 'COO'; return 'CEO / President'}
  function baseScore(v,map,def){return map[v]||def}
  function framework(i){if(i.industry.indexOf('Healthcare')>-1)return ['HIPAA Security Rule','NIST CSF']; if(i.industry.indexOf('Defense')>-1)return ['CMMC / NIST SP 800-171','NIST CSF']; if(i.industry.indexOf('Financial')>-1)return ['FFIEC / GLBA','NIST CSF']; if(i.industry.indexOf('Manufacturing')>-1)return ['NIST CSF','ISO 27001']; return ['NIST CSF','CIS Controls']}
  function exposureBase(i){var b={'Under $10M':250000,'$10M - $50M':900000,'$50M - $250M':2900000,'$250M+':8800000}[i.valueRange]||900000; if(i.dataSensitivity==='high')b*=1.45; if(i.evidence==='weak')b*=1.25; if(i.incident==='low')b*=1.3; if(i.controls==='high')b*=.72; return b}
  function generate(i){
    var trust=58+baseScore(i.controls,{low:-13,moderate:3,high:17},3)+baseScore(i.evidence,{weak:-16,partial:3,strong:15},3)+baseScore(i.incident,{low:-10,moderate:4,high:14},4)+baseScore(i.cadence,{reactive:-10,monthly:4,quarterly:0,continuous:13},4);
    var ai=66+baseScore(i.aiUse,{none:8,emerging:-2,shadow:-18,governed:17},-2)+baseScore(i.dataSensitivity,{low:8,moderate:0,high:-8},0);
    var confidence=62+baseScore(i.evidence,{weak:-18,partial:2,strong:22},2)+baseScore(i.controls,{low:-7,moderate:3,high:10},3);
    var exp=exposureBase(i); var range=[exp*.72,exp*1.85]; var sc={trust:pct(trust),ai:pct(ai),confidence:pct(confidence),exposurePressure:pct(100-(Math.min(95,trust*.55+confidence*.35+ai*.1)))};
    var actions=actionsFor(i,sc,range); var risks=risksFor(i,sc,range); var scenario=scenarioFor(i,sc,actions); var bubbles=bubblesFor(i,sc,range,framework(i),actions); var memory=memoryFor(i,sc,range,actions,risks);
    return {input:i,scores:sc,range:range,framework:framework(i),actions:actions,risks:risks,scenario:scenario,bubbles:bubbles,memory:memory,version:VERSION};
  }
  function actionsFor(i,s,range){
    var a=[]; function add(t,b,o,sev,age,score,conf){a.push({title:t,body:b,owner:o,severity:sev,age:age,score:score,confidence:conf,stage:stageFor(t)})}
    if(s.confidence<78)add('Run a 30-day evidence validation sprint','Collect current proof for controls, policies, vendor reviews, incident readiness, recovery, and AI governance before executives accept the posture.',i.recommendedOwner,'High',31,96,'Moderate');
    if(s.ai<76)add('Define the AI governance boundary','Identify approved AI tools, prohibited data, human approval points, prompt handling rules, and model use restrictions.','CIO / CTO','High',24,92,'Moderate');
    if(i.incident!=='high')add('Test the executive incident escalation chain','Run a tabletop around who decides, who communicates, who contacts counsel, who approves downtime, and who owns recovery sequencing.','COO','High',42,90,'High');
    if(!i.owner||i.owner==='Unassigned')add('Assign accountable risk treatment owners','Each top risk needs one accountable executive owner. Unowned risk becomes unresolved operational risk.','CEO / President','High',18,88,'High');
    if(i.primaryConcern==='vendor'||i.industry.indexOf('Manufacturing')>-1)add('Complete vendor governance review','Identify critical vendors, evidence gaps, contract exposure, continuity dependencies, and annual review cadence.','COO','Moderate',63,83,'Moderate');
    if(i.controls!=='high')add('Replace generic policies with owned controls','Map policies to owners, review dates, evidence requirements, and executive reporting cadence.','vCISO / Advisor','Moderate',57,78,'Moderate');
    if(i.evidence==='weak')add('Create an audit-ready evidence index','Build a simple evidence register for controls, policies, risk decisions, response artifacts, vendor reviews, and AI governance evidence.','CISO / Security Lead','High',45,86,'Limited');
    if(i.cadence==='reactive')add('Establish monthly operational trust review','Move cybersecurity governance from event-driven reaction to recurring executive operating rhythm.','CEO / President','Moderate',30,74,'High');
    add('Generate executive briefing artifact','Produce a concise board-ready summary covering what changed, why it matters, business impact, confidence, and recommended decisions.',i.recommendedOwner,'Moderate',0,70,'High');
    return a.sort(function(x,y){return y.score-x.score}).slice(0,8);
  }
  function stageFor(t){if(t.indexOf('evidence')>-1)return 'Evidence Maturity'; if(t.indexOf('AI')>-1)return 'AI Governance'; if(t.indexOf('incident')>-1)return 'Incident Readiness'; if(t.indexOf('owner')>-1)return 'Ownership'; if(t.indexOf('vendor')>-1)return 'Third-Party Governance'; if(t.indexOf('policies')>-1)return 'Control Ownership'; return 'Executive Reporting'}
  function risksFor(i,s,range){var r=[];function add(t,b,o,c){r.push({title:t,body:b,owner:o,cls:c})} if(s.confidence<76)add('Evidence confidence below executive decision threshold','Leadership may be forced to make risk decisions without enough current and reviewable evidence.',i.recommendedOwner,'red'); if(s.ai<76||i.primaryConcern==='ai')add('AI use outside a mature governance boundary','Sensitive data, unclear approved-use rules, and incomplete oversight can create trust-state drift.','CIO / CTO','yellow'); if(i.incident!=='high')add('Incident escalation chain not sufficiently tested','A high-consequence event can suffer delays in authority, communication, legal coordination, or recovery sequencing.','COO','red'); if(i.primaryConcern==='vendor')add('Third-party exposure visibility incomplete','Vendor dependencies can create cascading operational risk when ownership and evidence are weak.','COO','yellow'); if(r.length<3)add('Operational exposure requires executive treatment','The directional exposure range is high enough to require explicit risk treatment and ownership.',i.recommendedOwner,'yellow'); return r.slice(0,3)}
  function scenarioFor(i,s,actions){var type=i.primaryConcern==='ai'?'Shadow AI prompt leakage event':i.primaryConcern==='vendor'?'Vendor-origin ransomware staging':i.primaryConcern==='incident'?'Compromised executive identity escalation':'AI-enabled phishing against finance leadership';
    var telemetry=[['T+00','Unusual identity behavior','Identity signal','Leadership-adjacent account activity deviated from normal approval behavior.'],['T+06','Targeted executive lure','Email security signal','Finance or executive users received a message designed to influence approval behavior.'],['T+12','Privilege pathway pressure','Access review context','Submitted owner and control maturity indicate incomplete decision accountability.'],['T+24','Evidence gap confirmed','Governance signal','Evidence state may not support rapid containment, recovery, or board communication.']];
    var narrative={before:'Identity anomalies, targeted messages, and incomplete evidence exist across leadership-adjacent workflows.',after:'CyberShield interprets this as a potential adversarial coordination event that can degrade trust in identity, approval, recovery, and executive escalation decisions.',consequence:'The operational consequence is not only compromise risk. It is decision delay, payment disruption, vendor uncertainty, and reduced recovery confidence.',blast:['Finance approval workflow','Executive communications','Vendor payment confidence','Incident escalation timing','Recovery decision authority']};
    var decisions=[['Escalate now?','Escalate for evidence validation and owner review before accepting risk.',i.recommendedOwner,'High'],['Constrain affected workflows?','Temporarily tighten approval, vendor payment, and privileged access paths.','CIO / CTO','High'],['Proof required before closure?','Validated account review, backup recoverability, communication chain, vendor review, and documented risk treatment.','vCISO / Advisor','High'],['If nothing happens?','Exposure shifts from technical uncertainty to operational disruption, fraud risk, reputational loss, and delayed recovery decisions.','CEO / President','High']];
    return {type:type,telemetry:telemetry,narrative:narrative,decisions:decisions,primaryAction:actions[0]?actions[0].title:'Run executive evidence validation sprint'} }
  function bubblesFor(i,s,range,fw,actions){var control=baseScore(i.controls,{low:42,moderate:68,high:86},68),incident=baseScore(i.incident,{low:44,moderate:66,high:88},66),evidence=baseScore(i.evidence,{weak:38,partial:67,strong:90},67),owner=(!i.owner||i.owner==='Unassigned')?45:82,compliance=baseScore(i.evidence,{weak:52,partial:72,strong:88},72),data=baseScore(i.dataSensitivity,{low:84,moderate:66,high:48},66),velocity=baseScore(i.cadence,{reactive:43,monthly:72,quarterly:62,continuous:88},72),load=pct(100-Math.min(90,actions.length*8));return [['Operational Trust',s.trust,'Leadership readiness to make defensible cyber decisions'],['AI Governance',s.ai,'AI use inside or outside defined control boundaries'],['Evidence Confidence',s.confidence,'How much depends on evidence versus assumptions'],['Exposure Control',100-s.exposurePressure,'Directional exposure pressure requiring treatment'],['Evidence Maturity',evidence,'Current, organized, and reviewable evidence'],['Incident Readiness',incident,'Executive escalation and recovery confidence'],['Ownership Clarity',owner,'Named decision owners for unresolved risk'],['Control Ownership',control,'Policies and controls that are real, current, and owned'],['Compliance Lens',compliance,'Framework alignment: '+fw[0]],['Data Sensitivity',data,'Operational consequence of sensitive data exposure'],['Decision Velocity',velocity,'Speed of leadership action without chaos'],['Orchestration Load',load,'Remaining governance work requiring sequencing']]}
  function memoryFor(i,s,range,actions,risks){return [['Baseline briefing',i.date,i.orgName+' generated a '+i.reviewGoalLabel+' under '+i.industry+' context.'],['Accepted evidence state',cap(i.evidence),'Evidence maturity affects confidence and audit defensibility.'],['Unresolved risk count',risks.length+'', 'Top risks remain visible until treated, accepted, transferred, escalated, or investigated.'],['Open orchestration items',actions.length+'','Action queue persists locally to support governance continuity.'],['Exposure range',money(range[0])+' to '+money(range[1]),'Range is directional and based only on submitted inputs.'],['Recommended owner',i.recommendedOwner,'Owner selection should be validated during executive review.']]}
  function renderAll(){if(!state.data)return; renderBriefing();renderActions();renderScenario();renderTrust();renderMemory();renderReports();}
  function renderBriefing(){var d=state.data,i=d.input,s=d.scores,a=d.actions[0];$('#briefingTitle').textContent=i.orgName+' Executive Operational Briefing';$('#briefingMeta').textContent='Prepared for '+i.personName+' • '+i.date+' • '+i.reviewGoalLabel+' • '+d.framework[0];$('#briefingHeadline').textContent=a.title;$('#briefingSummary').textContent=a.body;$('#briefingStatus').innerHTML='<span class="'+cls(s.trust)+'">Trust '+s.trust+'%</span><span class="'+cls(s.ai)+'">AI '+s.ai+'%</span><span class="'+cls(s.confidence)+'">Confidence '+s.confidence+'%</span><span>Exposure '+money(d.range[0])+' - '+money(d.range[1])+'</span>';$('#executiveMetrics').innerHTML=[['Operational Trust',s.trust],['AI Governance',s.ai],['Confidence',s.confidence],['Exposure Control',100-s.exposurePressure]].map(metricCard).join('');$('#briefingChain').innerHTML=[['What changed',d.scenario.type],['Why it matters',d.scenario.narrative.after],['Operational consequence',d.scenario.narrative.consequence],['Leadership action',a.title],['Governance state','Unresolved for '+a.age+' days • Owner: '+a.owner]].map(function(x){return '<button class="chain-step" data-detail="'+esc(x[0])+'"><b>'+x[0]+'</b><span>'+x[1]+'</span></button>'}).join('');}
  function metricCard(x){var c=cls(x[1]);return '<button class="metric-card" data-detail="'+esc(x[0])+'"><b>'+x[0]+'</b><div class="score">'+x[1]+'%</div><span class="state '+c+'">'+band(x[1])+'</span><div class="heat"><span class="dot" style="left:'+x[1]+'%"></span></div></button>'}
  function renderActions(){var html=state.data.actions.map(function(a,idx){var p=a.severity==='High'?'high':'medium';return '<button class="action-card" data-action="'+idx+'"><span class="priority '+p+'">'+(idx+1)+'</span><span><b>'+a.title+'</b><p>'+a.body+'</p><span class="action-meta"><span>'+a.severity+' priority</span><span>Age: '+a.age+' days</span><span>Stage: '+a.stage+'</span><span class="owner">Owner: '+a.owner+'</span><span>Confidence: '+a.confidence+'</span></span></span></button>'}).join('');$('#actionQueue').innerHTML=html}
  function renderScenario(){var sc=state.data.scenario;$('#scenarioTimeline').innerHTML=sc.telemetry.map(function(t){return '<button class="timeline-item" data-detail="'+esc(t[1])+'"><b>'+t[0]+' • '+t[1]+'</b><span>'+t[3]+'</span><small>'+t[2]+'</small></button>'}).join('');$('#scenarioNarrative').innerHTML='<div class="translation"><div class="translation-card"><b>Before CyberShield</b><p>'+sc.narrative.before+'</p></div><div class="translation-card"><b>After CyberShield</b><p>'+sc.narrative.after+'</p></div><div class="translation-card"><b>Operational consequence</b><p>'+sc.narrative.consequence+'</p></div><div class="translation-card"><b>Blast radius</b><p>'+sc.narrative.blast.join(' • ')+'</p></div></div>';$('#decisionTable').innerHTML='<table><thead><tr><th>Decision</th><th>Guidance</th><th>Owner</th><th>Urgency</th></tr></thead><tbody>'+sc.decisions.map(function(r){return '<tr><td>'+r[0]+'</td><td>'+r[1]+'</td><td class="owner">'+r[2]+'</td><td>'+r[3]+'</td></tr>'}).join('')+'</tbody></table>'}
  function renderTrust(){$('#trustBubbles').innerHTML=state.data.bubbles.map(function(b){return '<button class="metric-card" data-detail="'+esc(b[0])+'"><b>'+b[0]+'</b><div class="score">'+pct(b[1])+'%</div><p>'+b[2]+'</p><span class="state '+cls(b[1])+'">'+band(b[1])+'</span><div class="heat"><span class="dot" style="left:'+pct(b[1])+'%"></span></div></button>'}).join('')}
  function renderMemory(){$('#memoryGrid').innerHTML=state.data.memory.map(function(m){return '<button class="memory-card" data-detail="'+esc(m[0])+'"><b>'+m[0]+'</b><div class="value">'+m[1]+'</div><p>'+m[2]+'</p></button>'}).join('')}
  var reportNames=['Executive Risk Summary','Operational Resilience Snapshot','Governance Drift Report','AI Governance Assessment','Vendor Governance Review','Board Briefing','Incident Readiness Summary','Security Roadmap'];
  function renderReports(){var pick=$('#reportPicker');pick.innerHTML=reportNames.map(function(n){return '<button class="'+(n===state.activeReport?'active':'')+'" data-report="'+n+'">'+n+'</button>'}).join('');renderReportPreview()}
  function renderReportPreview(){var d=state.data,i=d.input,a=d.actions.slice(0,3),r=d.risks;$('#reportPreview').innerHTML='<span class="report-tag">'+state.activeReport+'</span><h2>'+i.orgName+' Executive Intelligence Output</h2><p><b>Prepared for:</b> '+i.personName+' • <b>Date:</b> '+i.date+' • <b>Framework lens:</b> '+d.framework[0]+'</p><h3>Current organizational risk</h3><p>'+band(d.scores.trust)+' operational trust posture with '+band(d.scores.confidence).toLowerCase()+' evidence confidence. Directional exposure range: <b>'+money(d.range[0])+' to '+money(d.range[1])+'</b>.</p><h3>Top operational risks</h3><ol>'+r.map(function(x){return '<li><b>'+x.title+'</b>: '+x.body+' <em>Owner: '+x.owner+'</em></li>'}).join('')+'</ol><h3>Recommended priorities</h3><ol>'+a.map(function(x){return '<li><b>'+x.title+'</b>: '+x.body+' <em>Owner: '+x.owner+'</em></li>'}).join('')+'</ol><h3>Executive briefing scenario</h3><p>'+d.scenario.narrative.after+'</p><h3>Confidence and limitations</h3><p>Generated from submitted inputs. Not a verified audit, penetration test, forensic investigation, or legal opinion. Recommendations should be validated by Maximum Justice Cybersecurity, a vCISO, Security SME, and Cybersecurity SME advisory team.</p>'}
  function wireDynamic(){
    document.addEventListener('click',function(e){var a=e.target.closest('[data-action]'); if(a){var item=state.data.actions[+a.dataset.action];showDetail(item.title,item.body,'Owner: '+item.owner+' • Priority: '+item.severity+' • Confidence: '+item.confidence); updateAdvisor(item.title,item.body,item.owner)} var d=e.target.closest('[data-detail]'); if(d&&!a){showDetail(d.dataset.detail,'CyberShield surfaces this item because it affects operational trust, decision confidence, ownership, or governance continuity.','Selected item updates the executive reasoning layer.')} var r=e.target.closest('[data-report]'); if(r){state.activeReport=r.dataset.report;save();renderReports();}});
    $('#downloadReport').addEventListener('click',downloadReport);$('#emailReport').addEventListener('click',emailReport);$('#printReport').addEventListener('click',function(){window.print()});
  }
  function updateAdvisor(t,b,o){$('#advisorTitle').textContent=t;$('#advisorBody').innerHTML=b+'<br><br><span class="owner">Recommended owner: '+o+'</span>'}
  function showDetail(t,b,m){$('#dialogTitle').textContent=t;$('#dialogBody').textContent=b;$('#dialogMeta').textContent=m||'';$('#detailDialog').showModal()}
  function reportText(){var tmp=document.createElement('div'); tmp.innerHTML=$('#reportPreview').innerHTML; return tmp.innerText}
  function downloadReport(){var blob=new Blob([reportText()],{type:'text/plain'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='CyberShield_'+state.activeReport.replace(/\s+/g,'_')+'.txt';a.click();URL.revokeObjectURL(a.href)}
  function emailReport(){location.href='mailto:?subject='+encodeURIComponent('CyberShield '+state.activeReport)+'&body='+encodeURIComponent(reportText())}
  function esc(s){return String(s).replace(/"/g,'&quot;').replace(/</g,'&lt;')}
  function init(){load();wireRoutes();wireForm();wireDynamic();showStep(0);updateGate();if(state.data)renderAll();route((location.hash||'#overview').replace('#',''))}
  document.addEventListener('DOMContentLoaded',init);
})();
